export default [
  'USA',
  'Russia',
  'Brazil',
  'Spain',
  'UK',
  'Italy',
  'France',
  'Germany',
  'Turkey',
  'Iran',
  'India',
  'Peru',
  'China',
  'Canada',
  'Saudi Arabia',
  'Chile',
  'Mexico',
  'Belgium',
  'Pakistan',
  'Netherlands',
  'Qatar',
  'Ecuador',
  'Belarus',
  'Sweden',
  'Switzerland',
  'Singapore',
  'Bangladesh',
  'Portugal',
  'UAE',
  'Ireland',
  'Indonesia',
  'Poland',
  'Ukraine',
  'Kuwait',
  'South Africa',
  'Colombia',
  'Romania',
  'Israel',
  'Austria',
  'Japan',
  'Egypt',
  'Dominican Republic',
  'Philippines',
  'Denmark',
  'S. Korea',
  'Serbia',
  'Panama',
  'Argentina',
  'Afghanistan',
  'Czechia',
  'Bahrain',
  'Norway',
  'Algeria',
  'Kazakhstan',
  'Morocco',
  'Malaysia',
  'Australia',
  'Nigeria',
  'Oman',
  'Moldova',
  'Finland',
  'Ghana',
  'Armenia',
  'Bolivia',
  'Cameroon',
  'Luxembourg',
  'Iraq',
  'Azerbaijan',
  'Hungary',
  'Honduras',
  'Sudan',
  'Guinea',
  'Thailand',
  'Uzbekistan',
  'Senegal',
  'Greece',
  'Guatemala',
  'Bosnia and Herzegovina',
  'Bulgaria',
  'Tajikistan',
  'Ivory Coast',
  'Croatia',
  'Djibouti',
  'DRC',
  'North Macedonia',
  'Cuba',
  'Estonia',
  'Iceland',
  'El Salvador',
  'Lithuania',
  'Somalia',
  'Gabon',
  'New Zealand',
  'Slovakia',
  'Mayotte',
  'Slovenia',
  'Kyrgyzstan',
  'Maldives',
  'Kenya',
  'Guinea-Bissau',
  'Lebanon',
  'Hong Kong',
  'Sri Lanka',
  'Tunisia',
  'Latvia',
  'Albania',
  'Equatorial Guinea',
  'Mali',
  'Cyprus',
  'Niger',
  'Costa Rica',
  'Venezuela',
  'Zambia',
  'Paraguay',
  'Burkina Faso',
  'Andorra',
  'Uruguay',
  'Haiti',
  'Georgia',
  'Diamond Princess',
  'Jordan',
  'San Marino',
  'Sierra Leone',
  'Malta',
  'Chad',
  'Channel Islands',
  'Jamaica',
  'Nepal',
  'Tanzania',
  'South Sudan',
  'Congo',
  'Réunion',
  'Madagascar',
  'Taiwan',
  'CAR',
  'Ethiopia',
  'Palestine',
  'Cabo Verde',
  'Togo',
  'Isle of Man',
  'Mauritius',
  'Montenegro',
  'Vietnam',
  'Rwanda',
  'Nicaragua',
  'Sao Tome and Principe',
  'Liberia',
  'French Guiana',
  'Eswatini',
  'Myanmar',
  'Yemen',
  'Martinique',
  'Faeroe Islands',
  'Mauritania',
  'Mozambique',
  'Uganda',
  'Guadeloupe',
  'Gibraltar',
  'Brunei',
  'Mongolia',
  'Benin',
  'Guyana',
  'Bermuda',
  'Cambodia',
  'Cayman Islands',
  'Trinidad and Tobago',
  'Aruba',
  'Bahamas',
  'Monaco',
  'Barbados',
  'Liechtenstein',
  'Sint Maarten',
  'Libya',
  'Malawi',
  'Angola',
  'French Polynesia',
  'Syria',
  'Zimbabwe',
  'Macao',
  'Burundi',
  'Saint Martin',
  'Eritrea',
  'Comoros',
  'Botswana',
  'Antigua and Barbuda',
  'Gambia',
  'Timor-Leste',
  'Grenada',
  'Bhutan',
  'Laos',
  'Namibia',
  'Belize',
  'Fiji',
  'New Caledonia',
  'Saint Lucia',
  'St. Vincent Grenadines',
  'Curaçao',
  'Dominica',
  'Saint Kitts and Nevis',
  'Falkland Islands',
  'Turks and Caicos',
  'Vatican City',
  'Montserrat',
  'Suriname',
  'Greenland',
  'Seychelles',
  'MS Zaandam',
  'British Virgin Islands',
  'Papua New Guinea',
  'Caribbean Netherlands',
  'St. Barth',
  'Western Sahara',
  'Anguilla',
  'Lesotho',
  'Saint Pierre Miquelon',
];
